hdf5:
  - 1.14.3

gazebo:
  - 11

yaml-cpp:
  - 0.7

pcl:
  - 1.13
  
numpy:
  - 1.23

ogre:
  - 1.10.12

python:
  - 3.11.* *_cpython

python_impl:
  - cpython

graphviz:
  - 9

pin_run_as_build:
  graphviz:
    max_pin: x
  yaml-cpp:
    max_pin: x.x
  # hdf5: x.x.x
