hdf5:
  - 1.12.2

# gazebo:
#   - 11.12.0

yaml-cpp:
  - 0.7
  
numpy:
  - 1.26

python:
  - 3.9.* *_cpython

python_impl:
  - cpython

graphviz:
  - 6

pin_run_as_build:
  graphviz:
    max_pin: x
  yaml-cpp:
    max_pin: x.x
  # hdf5: x.x.x