# this sets up "context variables" (in this case name and version) that
# can later be used in Jinja expressions
context:
  version: 2.12.0
  name: xbot2

# top level package information (name and version)
package:
  name: "{{ name }}"
  version: "{{ version }}"

# location to get the source from
source: 
  path: ../../../xbot2

# build number (should be incremented if a new build is made, but version is not incrementing)
build:
  number: 1

# the requirements at build and runtime
requirements:
  host:
    - cmake
    - conda-build   
    - python
    - eigen
    - xbotinterface
    - gazebo 
    - ros-noetic-srdfdom
    - ros-noetic-tf
    - ros-noetic-tf2-kdl
    - ros-noetic-tf2-eigen
    - xbot_msgs

  run:
    - gazebo 
    - xbotinterface
    - ros-noetic-srdfdom
    - xbot_msgs
    - ros-noetic-tf
    - ros-noetic-tf2-kdl
    - ros-noetic-tf2-eigen

# tests to validate that the package works as expected
# test:
#   imports:
#     - imagesize

# information about the package
# about:
#   home: https://github.com/shibukawa/imagesize_py
#   license: MIT
#   summary: 'Getting image size from png/jpeg/jpeg2000/gif file'
#   description: |
#     This module analyzes jpeg/jpeg2000/png/gif image header and
#     return image size.
#   dev_url: https://github.com/shibukawa/imagesize_py
#   doc_url: https://pypi.python.org/pypi/imagesize
#   doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst

# # the below is conda-forge specific!
# extra:
#   recipe-maintainers:
#     - somemaintainer