name: conda_build_env

channels:
- conda-forge
- robostack-staging
- iit_hhcm

dependencies:
- python=3.9
- conda-build=3.27.0 
- conda-verify
- anaconda-client
- pip
- mamba
- pip:
  - git+https://github.com/mamba-org/boa@main
        
