name: conda_build_env

channels:
- conda-forge
- robostack-staging
- iit_hhcm

dependencies:
- python=3.9
- conda-build=3.27.0 
- conda-verify
- anaconda-client
- compilers 
- cmake
- numpy 
- pkg-config 
- make 
- ninja
- tinyxml
- ros-noetic-urdf
- ros-noetic-kdl-parser
- ros-noetic-eigen-conversions
- ros-noetic-cmake-modules
- ros-noetic-rosconsole-bridge
- orocos-kdl
- tinyxml
- yaml-cpp
- ros-noetic-ros-base 
- ros-noetic-tf
- ros-noetic-tf2-kdl
- ros-noetic-srdfdom
- gazebo
- hdf5=1.12.2
- pip
- colorama 
- ruamel 
- ruamel.yaml 
- rich 
- mamba
- jsonschema
- pip:
  - git+https://github.com/mamba-org/boa@main
        
