name: conda_test_env

channels:
- conda-forge
- robostack-staging
- iit_hhcm

dependencies:
- ros-noetic-desktop-full
- cartesian-interface
- xbot2
- modelinterfacerbdl
- xbot2-gui
- iit-centauro-ros-pkg
