name: conda_test_env

channels:
- conda-forge
- robostack-staging
- iit_hhcm

dependencies:
- python=3.11
- ros-noetic-desktop-full
# - ros-noetic-rosmon
- cartesian-interface
- xbot2
- modelinterfacerbdl
- xbot2-gui
- iit-centauro-ros-pkg
- protobuf=4.24.4
- compilers 
- cmake 
- pkg-config 
- make 
- ninja 
- colcon-common-extensions 
- catkin_tools 
- rosdep

