name: conda_test_env

channels:
- conda-forge
- robostack-staging
- iit_hhcm

dependencies:
- ros-noetic-desktop-full
- ros-noetic-rosmon
- cartesian-interface
- xbot2
- modelinterfacerbdl
- xbot2-gui
- iit-centauro-ros-pkg
- ros-noetic-geometric-shapes==0.7.3
- ros-noetic-gazebo-ros==2.9.2=py39h67aadc1_15
